[project]
name = "ctg_viz"
version = "0.1.0"
description = "Librería para análisis y visualización de CTG"
authors = [{name="Alexia"}]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ctg_viz"]
